### ISSUE TITLE
Fix typo in node configuration for kubelet service

### ISSUE THREAD

**Issue by vtlrazin** [nuagenetworks/nuage-kubernetes#160]
Please remove extra spaces in "--kubeconfig" parameter in the first raw.
It's must look like:

Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"

B.R.
Vitaliy R.

**Comment by pdellaert** [comment]
Took me way to long to look at this... sorry. Thought it got resolved a long time ago, it didn't. Fixed it now
