### ISSUE TITLE
script to push the kube status to an API

### ISSUE THREAD

**Issue by Srinivasa381224** [nuagenetworks/nuage-kubernetes#170]
Hi am srinivasa am new to this scripting i have one requirement in kubernetes i need to create a script that script has to push the kubernetes  status to an api kubernetes commands we need push all pods in cluster please help me to create script

**Comment by pdellaert** [comment]
Hi @Srinivasa381224,

Is your question related to Nuage Networks? As far as i can tell from your request, it isn't. 

Nuage Networks is an SDN solution with an integration in Kubernetes as a CNI plugin, we do not provide Kubernetes monitoring itself.

If you need a script or tool to monitor Kubernetes, there are several solutions out there in the world. Additionally, if you want to script something yourself, there's Python and Golang libraries to help out.

Regards,
Philippe
