### ISSUE TITLE
Deployment pod based for kubernetes

### ISSUE THREAD

**Issue by prasenforu** [nuagenetworks/nuage-kubernetes#31]
I am using kubernetes 1.6.4 & installation done using kubeadm and RBAC

any yml based installation for nuage deployment for above kubernetes cluster ?

**Comment by christx2** [comment]
hey there, we have a new CNI based plugin here : https://github.com/nuagenetworks/nuage-cni 
also feel free to ping us at opensource@nuagenetworks.net, and detail what you want to deploy and how, so we can assist...look forward to hear about your cluster deployment
